apiVersion: geopodautoplacing/v0
kind: MuPlacerConfig
metadata:
  name: test-config
  namespace: edge
spec:
  namespace: edge
  sync-period: 30s
  stabilization-window: 2m
  query-period: 2m  # no less than 1 minute
  prometheus-url: http://160.80.223.232:30000
  offload-delay-threshold: 130ms
  unoffload-delay-threshold: 100ms
  cloud-area:
    cluster: ""
    context: liqo-admin@kubernetes
    cost:
      cpu: 0
      memory: 0
  edge-area:
    cluster: ""
    context: liqo-admin@kubernetes
    
    cost:
      cpu: 1
      memory: 0
    istio-ingress-source-app: istio-ingress
    istio-ingress-namespace: istio-ingress
    netprobe-server: ""
    resource-scaling: 1
  network:
    netprober-server-edge: http://160.80.223.212:31051/httpnetprober-edge
    netprober-server-cloud: http://httpnetprober-cloud:8080
    cloud-edge-bps: 1000Mbps
    edge-cloud-bps: 1000Mbps
    edge-cloud-rtt: 100ms
  epamp:
    u-limit: 1
    # no-caching: False,
    # locked: 

  explicit-service-id : true
  services:
    - name: s0
      id: 0
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s0.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s0.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s0.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s0.yaml
    - name: s1
      id: 1
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s1.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s1.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s1.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s1.yaml
    - name: s2
      id: 2
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s2.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s2.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s2.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s2.yaml
    - name: s3
      id: 3
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s3.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s3.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s3.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s3.yaml
    - name: s4
      id: 4
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s4.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s4.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s4.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s4.yaml
    - name: s5
      id: 5
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s5.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s5.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s5.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s5.yaml
    - name: s6
      id: 6
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s6.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s6.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s6.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s6.yaml
    - name: s7
      id: 7
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s7.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s7.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s7.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s7.yaml
    - name: s8 
      id: 8
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s8.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s8.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s8.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s8.yaml
    - name: s9
      id: 9
      instances: 
        cloud-yamls: 
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/cloud/no-subzone-specified/mubench-01000-Deployment-s9.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/cloud/hpa-mubench-01000-Deployment-s9.yaml
        edge-yamls:
          - /Users/detti/muBench/SimulationWorkspace/affinity-yamls/no-region-specified/edge1/no-subzone-specified/mubench-01000-Deployment-s9.yaml
          - /Users/detti/muBench/SimulationWorkspace/hpa/edge1/hpa-mubench-01000-Deployment-s9.yaml
        